import { createRepository } from './storage.js';
import { appendTripleZero, calculatePeriodSummary, expensesForPeriod, formatMoneyInput, formatVnd, isValidDateKey, parsePositiveAmount, periodBounds, periodKeyForDate, shiftPeriodKey } from './logic.js';

const repository = createRepository(localStorage);
const loaded = repository.load();
const $ = selector => document.querySelector(selector);
const STATUS_COPY = { missing: 'Chưa nhập thu nhập kỳ này', ok: 'Còn trong kế hoạch', warning: 'Sắp dùng hết thu nhập kỳ này', exceeded: 'Đã chi vượt thu nhập kỳ này' };
let state;
let editingExpenseId = null;
let dirtyDialogId = null;
const systemTheme = matchMedia('(prefers-color-scheme: dark)');

function todayKey() { const date = new Date(); return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`; }
function announce(message) { $('#appStatus').textContent = message; window.setTimeout(() => { if ($('#appStatus').textContent === message) $('#appStatus').textContent = ''; }, 2400); }
function reportStorageError() { announce('Không thể lưu. Hãy kiểm tra dung lượng trên iPhone.'); }
function selectedBounds() { return periodBounds(state.selectedPeriodKey, state.cycleStartDay); }
function allSelectedPeriodExpenses() { return expensesForPeriod(state.expenses, selectedBounds()); }
function selectedExpenses() { return expensesForPeriod(state.expenses, selectedBounds(), state.selectedCategoryId); }
function effectiveTheme(choice) { return choice === 'system' ? (systemTheme.matches ? 'dark' : 'light') : choice; }
function applyTheme(choice) { const effective = effectiveTheme(choice); document.documentElement.dataset.theme = effective; $('#themeColor').content = effective === 'dark' ? '#09130F' : '#F4F7F5'; $('#themeButton').textContent = effective === 'dark' ? '☾' : '☼'; document.querySelectorAll('input[name="theme"]').forEach(radio => { radio.checked = radio.value === choice; }); }
function makeButton(label, className = '') { const button = document.createElement('button'); button.type = 'button'; button.textContent = label; if (className) button.className = className; return button; }

function render() {
  const bounds = selectedBounds(); const income = state.periodIncomes[state.selectedPeriodKey] ?? null; const summary = calculatePeriodSummary(income, allSelectedPeriodExpenses());
  $('#periodLabel').textContent = bounds.label; $('#periodRange').textContent = bounds.rangeLabel; $('#remainingLabel').textContent = summary.status === 'exceeded' ? 'Vượt' : 'Còn lại'; $('#remainingAmount').textContent = summary.remaining === null ? '—' : formatVnd(Math.abs(summary.remaining)); $('#periodStatus').textContent = STATUS_COPY[summary.status]; $('#incomeButton').textContent = income === null ? 'Nhập thu nhập' : formatVnd(income); $('#spentAmount').textContent = formatVnd(summary.spent); $('.progress').setAttribute('aria-valuenow', String(Math.min(100, Math.round(summary.percentageUsed ?? 0)))); $('.progress').setAttribute('aria-valuetext', summary.percentageUsed === null ? 'Chưa có thu nhập' : `Đã dùng ${Math.round(summary.percentageUsed)} phần trăm`); $('#progressFill').style.width = `${Math.min(100, summary.percentageUsed ?? 0)}%`; $('#summary').dataset.status = summary.status; renderCategoryFilter(); renderCategoryGrid(); renderExpenseList();
}

function renderCategoryFilter() {
  const container = $('#categoryFilter'); container.replaceChildren();
  const all = makeButton('Tất cả', 'filter-chip'); all.setAttribute('aria-pressed', String(state.selectedCategoryId === 'all')); all.addEventListener('click', () => { state.selectedCategoryId = 'all'; render(); }); container.append(all);
  state.categories.forEach(category => { const button = makeButton(`${category.emoji} ${category.name}`, 'filter-chip'); button.setAttribute('aria-pressed', String(state.selectedCategoryId === category.id)); button.addEventListener('click', () => { state.selectedCategoryId = category.id; render(); }); container.append(button); });
}
function renderCategoryGrid(selected = $('#categoryGrid').dataset.selected || state.lastCategory) {
  const grid = $('#categoryGrid'); grid.replaceChildren(); grid.dataset.selected = selected;
  state.categories.forEach(category => { const button = makeButton(`${category.emoji} ${category.name}`, 'category-option'); button.setAttribute('aria-pressed', String(selected === category.id)); button.style.setProperty('--category-color', category.color); button.addEventListener('click', () => renderCategoryGrid(category.id)); grid.append(button); });
}
function renderExpenseList() {
  const list = $('#expenseList'); list.replaceChildren(); const expenses = selectedExpenses();
  if (!expenses.length) { const empty = document.createElement('p'); empty.className = 'empty-state'; empty.textContent = state.selectedCategoryId === 'all' ? 'Chưa có khoản chi trong kỳ này.' : 'Danh mục này chưa có khoản chi.'; list.append(empty); return; }
  const groups = new Map(); expenses.forEach(expense => { if (!groups.has(expense.date)) groups.set(expense.date, []); groups.get(expense.date).push(expense); });
  for (const [date, items] of groups) { const section = document.createElement('section'); section.className = 'date-group'; const heading = document.createElement('h3'); heading.className = 'date-heading'; heading.textContent = date.split('-').reverse().join('/'); section.append(heading); items.forEach(expense => { const category = state.categories.find(item => item.id === expense.catId) ?? state.categories.find(item => item.id === 'other'); const row = document.createElement('article'); row.className = 'expense-row'; const icon = document.createElement('span'); icon.className = 'expense-icon'; icon.textContent = category?.emoji ?? '📌'; const copy = document.createElement('div'); copy.className = 'expense-copy'; const title = document.createElement('div'); title.className = 'expense-title'; title.textContent = expense.title; const cat = document.createElement('div'); cat.className = 'expense-category'; cat.textContent = category?.name ?? 'Khác'; copy.append(title, cat); const amount = document.createElement('strong'); amount.className = 'expense-amount'; amount.textContent = formatVnd(expense.amount); row.append(icon, copy, amount); const actions = document.createElement('div'); actions.className = 'expense-actions'; const edit = makeButton('Sửa'); edit.setAttribute('aria-label', `Sửa ${expense.title}`); edit.addEventListener('click', () => openExpenseEditor(expense.id)); const remove = makeButton('Xóa'); remove.className = 'danger-button'; remove.setAttribute('aria-label', `Xóa ${expense.title}`); remove.addEventListener('click', () => deleteExpense(expense.id)); actions.append(edit, remove); row.append(actions); section.append(row); }); list.append(section); }
}

function openIncomeEditor() { const input = $('#incomeAmount'); input.value = formatMoneyInput(state.periodIncomes[state.selectedPeriodKey] ?? ''); $('#incomeAmountError').textContent = ''; $('#incomeSheet').showModal(); requestAnimationFrame(() => input.focus({ preventScroll: true })); }
function saveIncome(event) { event.preventDefault(); const amount = parsePositiveAmount($('#incomeAmount').value); if (amount === null) { $('#incomeAmountError').textContent = 'Thu nhập phải lớn hơn 0.'; $('#incomeAmount').focus(); return; } try { repository.savePeriodIncome(state.selectedPeriodKey, amount); state.periodIncomes = { ...state.periodIncomes, [state.selectedPeriodKey]: amount }; $('#incomeSheet').close(); announce('Đã lưu thu nhập'); render(); } catch { $('#incomeAmountError').textContent = 'Không thể lưu trên iPhone.'; } }
function openExpenseEditor(expenseId = null) { editingExpenseId = expenseId; const expense = state.expenses.find(item => item.id === expenseId); $('#expenseTitle').textContent = expense ? 'Sửa khoản chi' : 'Thêm khoản chi'; $('#expenseAmount').value = expense ? formatMoneyInput(expense.amount) : ''; $('#expenseTitleInput').value = expense?.title ?? ''; $('#expenseDate').value = expense?.date ?? todayKey(); $('#categoryGrid').dataset.selected = expense?.catId ?? state.lastCategory; ['expenseAmountError', 'expenseTitleError', 'expenseDateError'].forEach(id => { $(`#${id}`).textContent = ''; }); renderCategoryGrid($('#categoryGrid').dataset.selected); $('#expenseSheet').showModal(); requestAnimationFrame(() => $('#expenseAmount').focus({ preventScroll: true })); }
function saveExpense(event) { event.preventDefault(); const amount = parsePositiveAmount($('#expenseAmount').value); const title = $('#expenseTitleInput').value.trim(); const date = $('#expenseDate').value; const categoryId = $('#categoryGrid').dataset.selected || 'other'; let valid = true; if (amount === null) { $('#expenseAmountError').textContent = 'Số tiền phải lớn hơn 0.'; valid = false; } if (!title || title.length > 80) { $('#expenseTitleError').textContent = 'Tiêu đề từ 1 đến 80 ký tự.'; valid = false; } if (!isValidDateKey(date)) { $('#expenseDateError').textContent = 'Ngày không hợp lệ.'; valid = false; } if (!valid) return; const next = editingExpenseId ? state.expenses.map(item => item.id === editingExpenseId ? { ...item, title, amount, date, catId: categoryId } : item) : [...state.expenses, { id: crypto.randomUUID(), title, amount, date, catId: categoryId }]; try { repository.saveExpenses(next); repository.saveLastCategory(categoryId); state.expenses = next; state.lastCategory = categoryId; $('#expenseSheet').close(); announce(editingExpenseId ? 'Đã cập nhật khoản chi' : 'Đã lưu khoản chi'); render(); } catch { announce('Không thể lưu khoản chi.'); } }
async function deleteExpense(expenseId) { const expense = state.expenses.find(item => item.id === expenseId); if (!expense || !(await confirmAction(`Xóa khoản chi “${expense.title}”?`, 'Xóa'))) return; try { const next = state.expenses.filter(item => item.id !== expenseId); repository.saveExpenses(next); state.expenses = next; announce('Đã xóa khoản chi'); render(); } catch { reportStorageError(); } }
function confirmAction(message, label) { return new Promise(resolve => { $('#confirmMessage').textContent = message; $('#confirmAction').textContent = label; const dialog = $('#confirmDialog'); const form = dialog.querySelector('form'); const done = event => { event.preventDefault(); dialog.close(); resolve(event.submitter?.value === 'confirm'); form.removeEventListener('submit', done); }; form.addEventListener('submit', done); dialog.showModal(); }); }

function renderCategoryManager() { const list = $('#categoryManagerList'); list.replaceChildren(); state.categories.forEach((category, index) => { const row = document.createElement('li'); row.className = 'category-manager-row'; const name = document.createElement('span'); name.textContent = `${category.emoji} ${category.name}`; const actions = document.createElement('span'); actions.className = 'category-actions'; const edit = makeButton('Sửa'); edit.addEventListener('click', () => openCategoryEditor(category)); const up = makeButton('↑'); up.disabled = index === 0; up.addEventListener('click', () => reorderCategory(index, index - 1)); const down = makeButton('↓'); down.disabled = index === state.categories.length - 1; down.addEventListener('click', () => reorderCategory(index, index + 1)); actions.append(up, down, edit); if (category.id !== 'other') { const remove = makeButton('Xóa'); remove.addEventListener('click', () => removeCategory(category)); actions.append(remove); } row.append(name, actions); list.append(row); }); }
function openCategoryEditor(category = null) { $('#categoryId').value = category?.id ?? ''; $('#categoryName').value = category?.name ?? ''; $('#categoryEmoji').value = category?.emoji ?? '📌'; $('#categoryColor').value = category?.color ?? '#64748B'; $('#categoryNameError').textContent = ''; $('#categoryEditor').showModal(); requestAnimationFrame(() => $('#categoryName').focus({ preventScroll: true })); }
function saveCategory(event) { event.preventDefault(); const id = $('#categoryId').value || `custom-${crypto.randomUUID()}`; const name = $('#categoryName').value.trim(); const emoji = $('#categoryEmoji').value.trim() || '📌'; const color = $('#categoryColor').value; if (!name || name.length > 40) { $('#categoryNameError').textContent = 'Tên danh mục từ 1 đến 40 ký tự.'; return; } if (state.categories.some(category => category.name === name && category.id !== id)) { $('#categoryNameError').textContent = 'Tên danh mục đã tồn tại.'; return; } const next = state.categories.some(category => category.id === id) ? state.categories.map(category => category.id === id ? { id, name, emoji, color } : category) : [...state.categories, { id, name, emoji, color }]; try { repository.saveCategories(next); state.categories = next; $('#categoryEditor').close(); renderCategoryManager(); render(); announce('Đã lưu danh mục'); } catch { announce('Không thể lưu danh mục.'); } }
function reorderCategory(from, to) { const next = [...state.categories]; [next[from], next[to]] = [next[to], next[from]]; try { repository.saveCategories(next); state.categories = next; renderCategoryManager(); renderCategoryGrid(); renderCategoryFilter(); } catch { reportStorageError(); } }
async function removeCategory(category) { if (!(await confirmAction(`Xóa “${category.name}”? Khoản chi sẽ chuyển sang Khác.`, 'Xóa'))) return; try { const result = repository.deleteCategory(category.id); state.expenses = result.expenses; state.categories = result.categories; renderCategoryManager(); render(); announce('Đã xóa danh mục'); } catch { reportStorageError(); } }

function saveCycleStartDay(event) { event.preventDefault(); const day = Number($('#cycleStartDay').value); if (!Number.isInteger(day) || day < 1 || day > 31) { $('#cycleStartDayError').textContent = 'Ngày bắt đầu từ 1 đến 31.'; return; } const finish = () => { try { repository.saveCycleStartDay(day); state.cycleStartDay = day; state.selectedPeriodKey = periodKeyForDate(todayKey(), day); state.selectedCategoryId = 'all'; $('#periodSettingsSheet').close(); render(); announce('Đã đổi ngày bắt đầu kỳ'); } catch { reportStorageError(); } }; if (day === state.cycleStartDay) { finish(); } else confirmAction(`Đổi ngày bắt đầu sang ngày ${day}? Các khoản chi cũ sẽ được nhóm lại theo kỳ mới nhưng không bị xóa.`, 'Đổi ngày').then(ok => { if (ok) finish(); }); }

if (!loaded.ok) { $('#storageError').hidden = false; $('#storageError').textContent = 'Silo không đọc được dữ liệu đang lưu và đã dừng ghi để tránh ghi đè.'; } else {
  const savedPeriod = sessionStorage.getItem('silo_selected_period');
  const selectedPeriodKey = /^\d{4}-(0[1-9]|1[0-2])$/.test(savedPeriod ?? '') ? savedPeriod : periodKeyForDate(todayKey(), loaded.state.cycleStartDay);
  if (savedPeriod) sessionStorage.removeItem('silo_selected_period');
  state = { ...loaded.state, selectedPeriodKey, selectedCategoryId: 'all' }; $('#app').inert = false; applyTheme(state.theme); render();
  $('#themeButton').addEventListener('click', () => $('#themeSheet').showModal()); $('#themeForm').addEventListener('change', event => { if (event.target.name !== 'theme') return; try { repository.saveTheme(event.target.value); state.theme = event.target.value; applyTheme(state.theme); $('#themeSheet').close(); } catch { reportStorageError(); } }); systemTheme.addEventListener('change', () => { if (state.theme === 'system') applyTheme('system'); });
  $('#previousPeriod').addEventListener('click', () => { state.selectedPeriodKey = shiftPeriodKey(state.selectedPeriodKey, -1); state.selectedCategoryId = 'all'; render(); }); $('#nextPeriod').addEventListener('click', () => { state.selectedPeriodKey = shiftPeriodKey(state.selectedPeriodKey, 1); state.selectedCategoryId = 'all'; render(); }); $('#periodPicker').addEventListener('click', () => { $('#cycleStartDay').value = state.cycleStartDay; $('#periodSettingsSheet').showModal(); }); $('#incomeButton').addEventListener('click', openIncomeEditor); $('#incomeForm').addEventListener('submit', saveIncome); $('#addExpense').addEventListener('click', () => openExpenseEditor()); $('#expenseForm').addEventListener('submit', saveExpense); $('#manageCategories').addEventListener('click', () => { renderCategoryManager(); $('#categorySheet').showModal(); }); $('#addCategoryButton').addEventListener('click', () => openCategoryEditor()); $('#categoryForm').addEventListener('submit', saveCategory); $('#periodSettingsForm').addEventListener('submit', saveCycleStartDay);
  document.addEventListener('click', event => { const button = event.target.closest('[data-triple-zero]'); if (!button) return; const input = document.getElementById(button.dataset.tripleZero); const digits = appendTripleZero(input.value); if (digits) { input.value = formatMoneyInput(digits); input.focus(); } }); document.addEventListener('input', event => { if (!['expenseAmount', 'incomeAmount'].includes(event.target.id)) return; const value = formatMoneyInput(event.target.value); event.target.value = value; event.target.setSelectionRange(value.length, value.length); dirtyDialogId = event.target.closest('dialog')?.id ?? dirtyDialogId; }); document.querySelectorAll('[data-close]').forEach(button => button.addEventListener('click', () => { const dialog = document.getElementById(button.dataset.close); if (dirtyDialogId === dialog.id && !confirm('Bỏ các thay đổi chưa lưu?')) return; dialog.close(); })); document.querySelectorAll('dialog').forEach(dialog => dialog.addEventListener('close', () => { dirtyDialogId = null; }));
  if (navigator.storage?.persist) navigator.storage.persist().catch(() => false);
  if ('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js').then(registration => { const showUpdate = () => { $('#updateBanner').hidden = false; $('#updateBanner').onclick = () => { if (dirtyDialogId) { announce('Hãy lưu hoặc đóng biểu mẫu trước khi cập nhật.'); return; } registration.waiting?.postMessage({ type: 'SKIP_WAITING' }); }; }; if (registration.waiting) showUpdate(); registration.addEventListener('updatefound', () => { const worker = registration.installing; worker?.addEventListener('statechange', () => { if (worker.state === 'installed' && navigator.serviceWorker.controller) showUpdate(); }); }); }).catch(() => false);
  let reloading = false; navigator.serviceWorker?.addEventListener('controllerchange', () => { if (reloading) return; reloading = true; sessionStorage.setItem('silo_selected_period', state.selectedPeriodKey); location.reload(); });
}
